language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - composer install

script:
  - phpunit --exclude-group=internet --coverage-clover=coverage.clover
  - wget https://scrutinizer-ci.com/ocular.phar
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi
